name: Build and Release AppImage

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libfuse2
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download FFmpeg
        run: |
          wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          tar xf ffmpeg-master-latest-linux64-gpl.tar.xz
          mv ffmpeg-master-latest-linux64-gpl/bin/ffmpeg ffmpeg
          chmod +x ffmpeg

      - name: Download appimagetool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Build AppImage
        run: |
          pyinstaller --noconfirm --onefile --windowed --name YoutubeGo \
            --add-data "assets:assets" \
            --add-data "ui/themes:ui/themes" \
            --add-data "ffmpeg:." \
            main.py

          rm -rf AppDir
          mkdir -p AppDir/usr/bin
          cp dist/YoutubeGo AppDir/usr/bin/
          cp assets/app.png AppDir/
          echo -e "[Desktop Entry]\nName=YoutubeGo\nExec=YoutubeGo\nIcon=app\nType=Application\nCategories=AudioVideo;Video;Utility;" > AppDir/YoutubeGo.desktop
          ln -sf usr/bin/YoutubeGo AppDir/AppRun
          chmod +x AppDir/AppRun

          ./appimagetool-x86_64.AppImage --appimage-extract-and-run AppDir

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: '*.AppImage'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
