name: Create Linux Qt ZIP

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-linux-zip:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build AppImage
        run: |
          pyinstaller --noconfirm --onedir --windowed --name YoutubeGo \
          --icon=assets/app.ico \
          --add-data "assets:assets" \
          --add-data "ui/themes:ui/themes" \
          --add-data "assets/app.png:assets" main.py


          
          mkdir -p appdir/usr/bin
          cp dist/YoutubeGo/YoutubeGo appdir/usr/bin/
          chmod +x appdir/usr/bin/YoutubeGo

          
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
          chmod +x appimagetool

          
          ./appimagetool appdir dist/YoutubeGo-x86_64.AppImage

      - name: Create zip
        run: |
          mkdir YoutubeGo-Linux
          cp dist/YoutubeGo-x86_64.AppImage YoutubeGo-Linux/
          cp QtLicense.md YoutubeGo-Linux/
          cp LICENSE YoutubeGo-Linux/
          cd YoutubeGo-Linux
          zip -r ../YoutubeGo-Linux.zip *

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: YoutubeGo-Linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
