name: Create Linux Qt ZIP

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-linux-zip:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build AppImage
        run: |
          pyinstaller ...  # AppImage build komutun burada olacak
          mv dist/YoutubeGo dist/YoutubeGo-x86_64.AppImage

      - name: Create zip
        run: |
          mkdir YoutubeGo-Linux
          cp dist/YoutubeGo-x86_64.AppImage YoutubeGo-Linux/
          cp QtLicense.md YoutubeGo-Linux/
          cp LICENSE YoutubeGo-Linux/
          cd YoutubeGo-Linux
          zip -r ../YoutubeGo-Linux.zip *

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: YoutubeGo-Linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
