name: Build and Release for macOS

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download FFmpeg
        run: |
          curl -L https://evermeet.cx/ffmpeg/ffmpeg-6.1.zip -o ffmpeg.zip
          unzip ffmpeg.zip
          chmod +x ffmpeg

      - name: Build macOS App and ZIP
        run: |
          pyinstaller --noconfirm --windowed --name YoutubeGo \
            --add-data "assets:assets" \
            --add-data "ui/themes:ui/themes" \
            --add-data "ffmpeg:." \
            main.py
          mkdir -p output
          cp -r dist/YoutubeGo.app output/
          cd output
          zip -r YoutubeGo-macOS.zip YoutubeGo.app

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: output/YoutubeGo-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
