name: Build and Release macOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download FFmpeg
        run: |
          curl -L https://evermeet.cx/ffmpeg/ffmpeg-6.1.zip -o ffmpeg.zip
          unzip ffmpeg.zip
          mkdir -p resources
          mv -f ffmpeg resources/ffmpeg
          chmod +x resources/ffmpeg

      - name: Build macOS App
        run: |
          pyinstaller --noconfirm --onedir --windowed --name YoutubeGo \
            --add-data "assets:assets" \
            --add-data "ui/themes:ui/themes" \
            --add-data "resources:resources" \
            main.py

          mkdir -p "YoutubeGo.app/Contents/MacOS"
          mkdir -p "YoutubeGo.app/Contents/Resources"
          cp -r dist/YoutubeGo/* "YoutubeGo.app/Contents/MacOS/"
          cp -r resources "YoutubeGo.app/Contents/Resources/"
          cp assets/app.icns "YoutubeGo.app/Contents/Resources/"

          # Create Info.plist
          cat > "YoutubeGo.app/Contents/Info.plist" << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleExecutable</key>
              <string>YoutubeGo</string>
              <key>CFBundleIconFile</key>
              <string>app.icns</string>
              <key>CFBundleIdentifier</key>
              <string>com.youtubego.app</string>
              <key>CFBundleName</key>
              <string>YoutubeGo</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>CFBundleShortVersionString</key>
              <string>4.4</string>
              <key>LSMinimumSystemVersion</key>
              <string>10.13</string>
              <key>NSHighResolutionCapable</key>
              <true/>
          </dict>
          </plist>
          EOL

          # Create DMG
          rm -f YoutubeGo.dmg
          hdiutil create -volname "YoutubeGo" -srcfolder "YoutubeGo.app" -ov -format UDZO "YoutubeGo.dmg"

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: 'YoutubeGo.dmg'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}