name: Run Pytest

on:
  push:
    branches: [ main, dev, test ]
  pull_request:
    branches: [ main, dev, test ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==7.4.3 pytest-qt==4.2.0 pytest-cov==4.1.0 pytest-mock==3.12.0
          pip install PyQt5>=5.15.11 yt-dlp>=2025.3.26 requests>=2.32.3 psutil>=7.0.0 rich>=13.9.4

      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Tests with xvfb
        run: |
          xvfb-run -a pytest tests/ --disable-warnings --maxfail=3 -v
