name: Windows Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'
      - 'core/**'
      - 'build_meta/**'
      - 'assets/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ui/**'
      - 'core/**'
      - 'build_meta/**'
      - 'assets/**'

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install Pillow numpy
        
    - name: Install FFmpeg
      shell: powershell
      run: |
        choco install ffmpeg -y
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        Write-Host "FFmpeg version:"
        ffmpeg -version
        
    - name: Run all tests
      env:
        PYTHONPATH: ${{ github.workspace }}
        PYTEST_TIMEOUT: 30
      run: |
        pytest tests/ -v --tb=short --durations=0 --timeout=30 