name: Build and Release YoutubeGo

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download FFmpeg
        run: |
          $ffmpegUrl = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
          $outputPath = "ffmpeg.zip"
          Invoke-WebRequest -Uri $ffmpegUrl -OutFile $outputPath
          Expand-Archive -Path $outputPath -DestinationPath "ffmpeg"
          Move-Item -Path "ffmpeg/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe" -Destination "ffmpeg.exe"

      - name: Update Manifest Version
        run: |
          $tag = "${{ github.ref_name }}"
          $version = $tag -replace 'v', ''
          $manifestPath = "build_meta/YoutubeGo.manifest"
          $manifestContent = Get-Content $manifestPath -Raw
          $manifestContent = $manifestContent -replace 'version="[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"', "version=`"$version.0`""
          $manifestContent = $manifestContent -replace 'Version [0-9]+\.[0-9]+\.[0-9]+', "Version $version"
          Set-Content -Path $manifestPath -Value $manifestContent

      - name: Build YoutubeGo EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --name YoutubeGo `
            --icon=assets/app.ico `
            --add-data "assets;assets" `
            --add-data "ui/themes;ui/themes" `
            --add-data "assets/app.png;assets" `
            --add-data "assets/app.ico;assets" `
            --add-data "ffmpeg.exe;." `
            --manifest "build_meta/YoutubeGo.manifest" `
            main.py

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/YoutubeGo.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
